### ISSUE TITLE
linux-xlnx-v2020.2-zynqmp-fpga-xlnx_gem_alignment_size.diff failes to build with Petalinux 2021.1

### ISSUE THREAD

**Issue by p00chie** [ikwzm/ZynqMP-FPGA-Ubuntu20.04-Lima-Ultra96#2]
Hi, 

the patch linux-xlnx-v2020.2-zynqmp-fpga-xlnx_gem_alignment_size.diff failes to build with Petalinux 2021.1

I get this error message:
```
 /mnt/e/Petalinux/Vivado_21/Project_Testing/st1_msc/petalinux/st1_msc/build/tmp/work-shared/zynqmp-generic/kernel-source/drivers/gpu/drm/xlnx/xlnx_gem.c:29:39: error: expected ')' before 'int'
|    29 | module_param(     gem_alignment_size , int, S_IRUGO);
|       |                                       ^~~~
|       |                                       )
| /mnt/e/Petalinux/Vivado_21/Project_Testing/st1_msc/petalinux/st1_msc/build/tmp/work-shared/zynqmp-generic/kernel-source/drivers/gpu/drm/xlnx/xlnx_gem.c:30:39: error: expected ')' before string constant
|    30 | MODULE_PARM_DESC( gem_alignment_size , "xlnx gem alignment size");
|       |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                       )

```

Do you think it's a petalinux issue or maybe it's because of Kernel 5.10?

**Comment by p00chie** [comment]
I think 
#include <linux/module.h>
is missing in the patch

**Comment by ikwzm** [comment]
Thank you for valuable information

**Comment by p00chie** [comment]
I will try to use the lima driver too.
In the past i was lucky enough to get it working but had to modify the mesa sources because of some alignment errors.
I think/hope you have fixed it with this patch :)

**Comment by ikwzm** [comment]
Although it is in Japanese, I wrote an article that explained it. please refer.

https://qiita.com/ikwzm/items/642df8c14fd3a9e782b6
https://qiita.com/ikwzm/items/91adfcf05e767d33be70
https://qiita.com/ikwzm/items/ec29ae456ead67438733
https://qiita.com/ikwzm/items/ed2ce2d8bb90391d7c65
https://qiita.com/ikwzm/items/5c4c0114c15cfba8e95b
https://qiita.com/ikwzm/items/4dfb8f06ddf9d59e310c
https://qiita.com/ikwzm/items/21a59e68d30ad9faad6a

**Comment by p00chie** [comment]
These are very useful informations. Thx for your hard work.
Just to let you know. 
I switched to Ubuntu 21.04, compiled the mesa libs and switched to wayland.

Here is a output log of glmark2

```
=======================================================
    glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     lima
    GL_RENDERER:   Mali400
    GL_VERSION:    OpenGL ES 2.0 Mesa 21.0.3 (git-091978e0ec)
=======================================================
[build] use-vbo=false: FPS: 672 FrameTime: 1.488 ms
[build] use-vbo=true: FPS: 736 FrameTime: 1.359 ms
[texture] texture-filter=nearest: FPS: 787 FrameTime: 1.271 ms
[texture] texture-filter=linear: FPS: 755 FrameTime: 1.325 ms
[texture] texture-filter=mipmap: FPS: 771 FrameTime: 1.297 ms
[shading] shading=gouraud: FPS: 445 FrameTime: 2.247 ms
[shading] shading=blinn-phong-inf: FPS: 329 FrameTime: 3.040 ms
[shading] shading=phong: FPS: 212 FrameTime: 4.717 ms
[shading] shading=cel: FPS: 137 FrameTime: 7.299 ms
[bump] bump-render=high-poly: FPS: 154 FrameTime: 6.494 ms
[bump] bump-render=normals: FPS: 427 FrameTime: 2.342 ms
[bump] bump-render=height: FPS: 331 FrameTime: 3.021 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 134 FrameTime: 7.463 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 46 FrameTime: 21.739 ms
[pulsar] light=false:quads=5:texture=false: FPS: 1106 FrameTime: 0.904 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 42 FrameTime: 23.810 ms
[desktop] effect=shadow:windows=4: FPS: 361 FrameTime: 2.770 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 123 FrameTime: 8.130 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 119 FrameTime: 8.403 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 159 FrameTime: 6.289 ms
[ideas] speed=duration: FPS: 176 FrameTime: 5.682 ms
[jellyfish] <default>: FPS: 102 FrameTime: 9.804 ms
[terrain] <default>: Unsupported
[shadow] <default>: FPS: 184 FrameTime: 5.435 ms
[refract] <default>: FPS: 28 FrameTime: 35.714 ms
[conditionals] fragment-steps=0:vertex-steps=0: FPS: 467 FrameTime: 2.141 ms
[conditionals] fragment-steps=5:vertex-steps=0: FPS: 210 FrameTime: 4.762 ms
[conditionals] fragment-steps=0:vertex-steps=5: FPS: 469 FrameTime: 2.132 ms
[function] fragment-complexity=low:fragment-steps=5: FPS: 290 FrameTime: 3.448 ms
[function] fragment-complexity=medium:fragment-steps=5: FPS: 135 FrameTime: 7.407 ms
[loop] fragment-loop=false:fragment-steps=5:vertex-steps=5: FPS: 290 FrameTime: 3.448 ms
[loop] fragment-steps=5:fragment-uniform=false:vertex-steps=5: FPS: 290 FrameTime: 3.448 ms
[loop] fragment-steps=5:fragment-uniform=true:vertex-steps=5: FPS: 100 FrameTime: 10.000 ms
=======================================================
                                  glmark2 Score: 330 
=======================================================
```

So far so good and no gfx errors so far.
I don't know if the GEM fix is in place because i don't see and kenerel messages from DRM_DEBUG() but i didn't checked this function if it will output anything at all. bootargs is also in place.
Using Petalinux 2021.1 and lima in kernel 5.10 together with Ubuntu21.04.

**Comment by ikwzm** [comment]
Thank you for valuable information.
I would be very happy if you could publish your useful results.
